# docker-compose.yml
version: "3.8"

services:
    kurento:
        image: kurento/kurento-media-server:latest
        container_name: kurento-con
        restart: always
        ports:
            - "8888:8888"
            - "5000:5000"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    notification-service:
        image: laminhtam/social-media-notification-service:latest
        container_name: notification-service-con
        restart: always
        ports:
            - "8087:8087"
        environment:
            - CONFIG_SERVER_URL=https://config-server-q064.onrender.com
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

networks:
    backend:
