# docker-compose.yml
version: "3.8"

services:
    kurento:
        image: kurento/kurento-media-server:latest
        container_name: kurento-con
        restart: always
        ports:
            - "8888:8888"
            - "5000:5000"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    service-registry:
        image: laminhtam/social-media-service-registry:latest
        container_name: service-registry-con
        ports:
            - "8761:8761"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
                reservations:
                    memory: 128M
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:8761/actuator/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s

    config-server:
        image: laminhtam/social-media-config-server:latest
        container_name: config-server-con
        ports:
            - "8889:8889"
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
                reservations:
                    memory: 128M

    gateway:
        image: laminhtam/social-media-api-gateway:latest
        container_name: gateway-con
        restart: always
        ports:
            - "8060:8060"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        networks:
            - backend
        depends_on:
            service-registry:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    auth-service:
        image: laminhtam/social-media-auth-service:latest
        container_name: auth-service-con
        restart: always
        ports:
            - "9004:9004"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        depends_on:
            service-registry:
                condition: service_healthy
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    user-service:
        image: laminhtam/social-media-user-service:latest
        container_name: user-service-con
        restart: always
        ports:
            - "8082:8082"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        depends_on:
            service-registry:
                condition: service_healthy
        networks:
            - backend

    chat-service:
        image: laminhtam/social-media-chat-service:latest
        container_name: chat-service-con
        restart: always
        ports:
            - "8086:8086"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        depends_on:
            service-registry:
                condition: service_healthy
        networks:
            - backend

    post-service:
        image: laminhtam/social-media-post-service:latest
        container_name: post-service-con
        restart: always
        ports:
            - "8083:8083"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        depends_on:
            service-registry:
                condition: service_healthy
        networks:
            - backend

    notification-service:
        image: laminhtam/social-media-notification-service:latest
        container_name: notification-service-con
        restart: always
        ports:
            - "8087:8087"
        environment:
            - CONFIG_SERVER_URL=http://config-server:8889
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        depends_on:
            service-registry:
                condition: service_healthy
        networks:
            - backend

    # nextjs14-social-media-fe:
    #     image: dinhthong17/nextjs14-social-media-fe:latest
    #     container_name: nextjs14-social-media-fe-con
    #     restart: always
    #     ports:
    #         - "3000:3000"
    #     networks:
    #         - frontend

networks:
    backend:
    frontend:
