# docker-compose.yml
version: "3.8"

services:
    kurento:
        image: kurento/kurento-media-server:latest
        container_name: kurento-con
        restart: always
        ports:
            - "8888:8888"
            - "5000:5000"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    notification-service:
        image: laminhtam/social-media-notification-service:latest
        container_name: notification-service-con
        restart: always
        ports:
            - "8087:8087"
        environment:
            - CONFIG_SERVER_URL=https://config-server-q064.onrender.com
            - KURENTO_WS_URL=ws://kurento-con:8888/kurento
        networks:
            - backend
        depends_on:
            - kurento
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M

    proxy:
        image: nginx:latest
        container_name: nginx-con
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
                reservations:
                    memory: 128M

networks:
    backend:
