server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:service-registry-p3hn.onrender.com}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:https://service-registry-p3hn.onrender.com/eureka/}
