spring:
  application:
    name: post-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}"
logging:
  level:
    org.springframework.data.neo4j.cypher.deprecation: ERROR,