spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:https://config-server-q064.onrender.com}"

kurento:
  ws:
    url: "ws://localhost:8888/kurento"