server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}"
  data:
    mongodb:
      port: 27017
      host: localhost
      database: chat_db
      authentication-database: admin
      uri: mongodb://root:123456@localhost:27017/admin
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 60000
      password: 123456
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
jwt:
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1